spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_admin?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ypj94klys0ge
    password: U4ux7kaXgS7jto1e
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 13
    host: 192.168.0.189
    password: mht123
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s

# 七牛云文件上传配置
qiniu:
  accessKey: d0JQ8Oyoz9wvRvbWzHTt
  secretKey: d0JQ8Oyoz9wvRvbWzHTt
  bucketName: 3b52
  fileDomain: https://images.baidu.com

# mybatis-plus 打印 sql 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
