spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_admin?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true

# 七牛云文件上传配置
qiniu:
  accessKey: 123
  secretKey: 456
  bucketName: hello
  fileDomain: https://image.baidu.com

# mybatis-plus 打印 sql 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
