server:
  port: 18888

spring:
  profiles:
    active: dev
  application:
    name: spring-restful-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true


# mybatis-plus 自动配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xaaef.robin.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


# OAuth2.0 Server 配置
jwt:
  token:
    token-expired: 7200                 # 2小时
    exclude-path:
      - "/auth/sms/send"                     # 手机短信验证码 发送验证码
      - "/auth/sms"                          # 手机短信验证码 模式接口
      - "/auth/login"                        # 密码登录
      - "/auth/captcha/codes/**"             # 验证码接口


# knife4j 配置
knife4j:
  enable: true
  production: false
customize:
  swagger:
    title: 认证服务
    description: 认证服务 HTPP API 接口文档
    version: 3.0
    name: 王逗逗
    email: 932560435@qq.com
    url: https://xaaef.com
    service-url: http://localhost:18888/doc.html


info:
  app:
    name: ${customize.swagger.title}
    description: ${customize.swagger.description}
    version: ${customize.swagger.version}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
